mapbox/MapboxGeocoder.swift

- MBGeocoder/MapboxGeocoder.swift
Making this more like MapboxDirections and using a typed `JSON` alias. 
Only one issue: @1ec5 can you get a sense if what I'm doing with `decodeObjectOfClass:` for `MBPlacemark` is ok? i.e. casting `NSDictionary.self` as `JSON`. I'm not sure how else to implement the `NSSecureCoding` adoption.
> replace use of Foundation collections with typed container JSON alias

- MapboxGeocoder.xcodeproj/project.pbxproj
- MapboxGeocoder/MBGeocoder.swift
- MapboxGeocoder/MBGeocoderConfiguration.swift
- MapboxGeocoder/MBGeocoderRouter.swift
- MapboxGeocoderTests/ReverseGeocodingTests.swift
- Podfile
This PR rewrites the request logic based on RequestKit, along the lines of mapbox/MapboxDirections.swift#23.
Also exposed some additional options for geocoding.
> Rewrote request logic based on RequestKit

- MapboxGeocoder.xcodeproj/project.pbxproj
- Podfile
Moves the Podfile to individually named targets, as defined in the Xcode project. This is required for [CocoaPods 1.0.0](http://blog.cocoapods.org/CocoaPods-1.0/).
Refs https://github.com/mapbox/MapboxDirections.swift/pull/35
/cc @1ec5
> Convert Podfile to individual targets for CocoaPods 1.0.0

- MapboxGeocoder/MBGeocoder.swift
- MapboxGeocoderTests/ForwardGeocodingTests.swift
- MapboxGeocoderTests/ReverseGeocodingTests.swift
Allow client code to manage any number of running tasks. `cancelGeocode()` cancels all outstanding tasks.
Depends on nerdishbynature/RequestKit#13 and nerdishbynature/RequestKit#14.
/cc @tmcw
> Support concurrent requests

- MapboxGeocoder/MBGeocodeOptions.swift
Added an initializer to ForwardGeocodeOptions that takes a postal address. Whereas Core Location’s `CLGeocoder.geocodeAddressDictionary(_:completionHandler:)` takes an Address Book–style address dictionary, ForwardGeocodeOptions takes a CNPostalAddress object. The Contacts framework is only available in iOS 9.0 and above, but it’s intended to be a replacement for the Address Book framework.
Fixes #2.
> Forward geocode CNPostalAddress

- Geocoder Example/ViewController.m
- MapboxGeocoder/MBGeocoder.swift
- MapboxGeocoder/MBPlacemark.swift
- README.md
These classes need to be public to facilitate archiving.
> Took GeocodedPlacemark, QualifyingPlacemark public

- MapboxGeocoder/MapboxGeocoder.h
Fixed a crash loading the framework due to Contacts not being linked. The framework now includes the Contacts umbrella header, which means it probably won’t build against the iOS 8.x and OS X 10.10.x SDKs, but it’ll still deploy backwards to them.
/ref #41, #42
> Fix Contacts framework loading crash on OS X

- MapboxGeocoder.swift.podspec
- MapboxGeocoder.xcodeproj/project.pbxproj
- MapboxGeocoder.xcodeproj/xcshareddata/xcschemes/MapboxGeocoder tvOS.xcscheme
- MapboxGeocoder.xcodeproj/xcshareddata/xcschemes/MapboxGeocoder watchOS.xcscheme
- MapboxGeocoder/MBGeocodeOptions.swift
- MapboxGeocoder/MBPlacemark.swift
- MapboxGeocoder/MapboxGeocoder.h
- Podfile
- README.md
It’s been possible to use the pod in tvOS and watchOS since baf7dcf09067a72de41908035998560844dd9dab, although tvOS support broke when we added integration with the Contacts framework in #41 and #42. (Contacts is unavailable on tvOS. The breakage was fixed in #45.) To prevent similar breakage in the future, this PR adds tvOS and watchOS targets that can be built in CI.
/ref mapbox/MapboxStatic.swift#25
/cc @tmcw @friedbunny
> Support tvOS, watchOS

- MapboxGeocoder/MBGeocoder.swift
When the Geocoder object sends a request, it sets the `User-Agent` HTTP header to a value of the form:
```
SanDiego/1.2.3 MapboxGeocoder/0.5.0 iOS/9.3.0 (x86_64)
```
This user agent string is based on the one used by the Mapbox iOS and OS X SDKs.
Fixes #25.
> Configure user agent string

- MapboxGeocoder/MBGeocodeOptions.swift
Added a `locale` option that corresponds to the `language` query parameter and defaults to `nil`, in recognition of the query parameter’s experimental nature.
/cc @apendleton
> Add locale option

- MapboxGeocoder/MBGeocoder.swift
When the API reports an input error, there will be data and no HTTP error, but we still need to send the completion handler an NSError.
/ref mapbox/MapboxDirections.swift@4ed92bf692e2ea120c972041d56e6ea92fda2d34
> Pass through error messages

- Geocoder Example/ViewController.m
- Geocoder Example/ViewController.swift
- MapboxGeocoder.xcodeproj/project.pbxproj
- Podfile
Though showing Mapbox Geocoding API results atop a MapKit map shows how versatile this library can be, this usage also happens to violate the [Mapbox Geocoding API terms of service](https://www.mapbox.com/tos/#[YmouYmoq]) for free geocoding. This change replaces every instance of “MK” with “MGL”, showing just how easy it is to switch from MapKit to the Mapbox iOS SDK.
> Replace MapKit with Mapbox iOS SDK

- MapboxGeocoder/MBGeocoder.swift
For consistency with the Mapbox macOS SDK, the user agent string now says “macOS” instead of “OS X” on the Mac.
/cc @mick
> OS X → macOS

- Geocoder Example/ViewController.m
- MapboxGeocoder/MBPlacemarkScope.h
- MapboxGeocoder/MBPlacemarkScope.swift
`NS_SWIFT_NAME` doesn’t work very well on an enumeration inside a Swift framework.
Fixes #59, fixes #60.
/cc @incanus @friedbunny
> Export both MBPlacemarkScope and PlacemarkScope

- MapboxGeocoder/MBGeocoder.swift
Fixed an assertion failure that could occur (instead of an error being passed to the completion handler) if the response data was not the expected JSON format. This can happen, for instance, on a captive network.
For consistency with mapbox/MapboxDirections.swift#72, this PR avoids checking the response’s status code at this particular point.
/cc @willwhite
> Avoid deserializing non-JSON response data

- MapboxGeocoder/MBGeocoder.swift
- MapboxGeocoderTests/ForwardGeocodingTests.swift
- MapboxGeocoderTests/ReverseGeocodingTests.swift
Fixed a regression introduced in #71, which assumed that parseable API responses always have the MIME type `application/json`. In fact, API responses always have the `application/vnd.geo+json` MIME type except for certain kinds of errors, like the one for an incorrect access token.
/cc @bsudekum @frederoni @willwhite
> Accept application/vnd.geo+json MIME type

- MapboxGeocoder/MBRectangularRegion.swift
- MapboxGeocoderTests/ForwardGeocodingTests.swift
This crashed because `RectangularRegion` didn't properly conform to `CustomStringConvertible` the way its superclass `CLRegion` does and thus couldn't be converted into the necessary URL parameters.
> fix crash in allowedRegion use & add test

- MapboxGeocoder.xcodeproj/xcshareddata/xcschemes/Example (Objective-C).xcscheme
- MapboxGeocoder.xcodeproj/xcshareddata/xcschemes/Example (Swift).xcscheme
We didn't have all test targets on the Swift scheme nor any on the Objective-C one.
> flesh out all test targets for both Objective-C & Swift

- MapboxGeocoder.xcodeproj/project.pbxproj
- MapboxGeocoder/MBPlacemark.swift
- MapboxGeocoder/MBPlacemarkScope.h
- MapboxGeocoder/MBPlacemarkScope.swift
- MapboxGeocoderTests/ForwardGeocodingTests.swift
- MapboxGeocoderTests/PlacemarkScopeTests.swift
Fixed an issue causing landmark placemarks to have no scope. Also renamed and renumbered the `Landmark` scope. Now enabling points of interest automatically enables landmarks.
/cc @incanus
> Fix landmark roundtripping

- MapboxGeocoder/MBGeocoder.swift
- MapboxGeocoderTests/GeocoderTests.swift
This is not a fix for #90. Wasn't able to reproduce it so far — maybe something related to the Swift optimisation.
However, the parsing of the header fields in a case of the rate limit being hit had multiple problems:
* Use of lowercase header names. The header in the server response are uppercase (`x-rate-limit-interval` vs `X-Rate-Limit-Interval`)
* It was expected that the `allHeaderFields` dict contains values in the respective data type. However, the dict just contains the values as strings.
This PR
* fixes the mentioned problems
* exposes the `descriptiveError` function in the module (not public) for making it testable
* adds a test to verify the behaviour
> Fixed parsing of the rate limit error response

- MapboxGeocoder.xcodeproj/project.pbxproj
- MapboxGeocoder.xcodeproj/xcshareddata/xcschemes/Example (Objective-C).xcscheme
- MapboxGeocoder.xcodeproj/xcshareddata/xcschemes/MapboxGeocoder iOS.xcscheme
- MapboxGeocoder.xcodeproj/xcshareddata/xcschemes/MapboxGeocoder tvOS.xcscheme
- MapboxGeocoder.xcodeproj/xcshareddata/xcschemes/MapboxGeocoder watchOS.xcscheme
- Podfile
- Podfile.lock
Upgraded to Xcode 8.2, CocoaPods 1.2, iOS SDK v3.4.1, and OHHTTPStubs v5.2.3. Fixed CocoaPods warnings about `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` being overridden.
> Xcode 8.2, CocoaPods 1.2

- MapboxGeocoder.xcodeproj/project.pbxproj
Using `import Contacts` in the Swift geocoder itself isn't enough for the Objective-C example app compile to work. 
```
dyld: Library not loaded: @rpath/libswiftContacts.dylib
Referenced from: /Users/incanus/Library/Developer/Xcode/DerivedData/MapboxGeocoder-awwlcbzvkqzlhcczdgadmvdodsam/Build/Products/Debug-iphonesimulator/MapboxGeocoder.framework/MapboxGeocoder
Reason: image not found
(lldb) 
```
This links `Contacts.framework` specifically on the iOS, macOS, and watchOS geocoder targets to make things work in Objective-C projects.
> link Contacts framework for Objective-C build needs

- Geocoder Example/ViewController.m
- MapboxGeocoder/MBGeocoder.swift
- README.md
Also remvoed the batch geocoding example in Objective-C, since that method uses generics and therefore doesn’t bridge to Objective-C.
> Refine shared property, geocode methods

- Cartfile.private
- Cartfile.resolved
- MapboxGeocoderTests/ForwardGeocodingTests.swift
- MapboxGeocoderTests/ReverseGeocodingTests.swift
Resolved some Swift 3.1 compiler warnings in unit test code. Some optionals should’ve been force-unwrapped because they’d only be used if the optional turned out to be `nil`.
Also updated dependencies.
/cc @bsudekum
> Fix Swift 3.1 compatibility

- MapboxGeocoder/MBGeocoder.swift
Inlined HTTPURLResponse extension constants, which were only being used in one place each and would be unlikely to change. These static constants were being bridged to Objective-C as class properties on categories, but they were triggering linker warnings about “incompatible Objective-C category definitions” in object files when bridged to Objective-C.
/cc @frederoni
> Inline HTTPURLResponse extension constants

- Cartfile.resolved
- MapboxGeocoder.xcodeproj/project.pbxproj
- MapboxGeocoder/MBGeocoder.swift
Porting https://github.com/mapbox/MapboxDirections.swift/pull/153.
Local macOS tests wouldn’t run because they didn’t see the Carthage frameworks, so I fixed that (the MapboxDirections project already had this set). Unsure why this would have worked on CI previously.
/cc @1ec5
> Fix time format in error string

- MapboxGeocoder.xcodeproj/project.pbxproj
- README.md
The Objective-C example was failing to load the Swift version of the Contacts framework, as required by MapboxGeocoder. Follows up on https://github.com/mapbox/MapboxGeocoder.swift/pull/83.
```
dyld: Library not loaded: @rpath/libswiftContacts.dylib
Referenced from: /Library/Developer/Xcode/DerivedData/MapboxGeocoder-forgxhxxjpxndqethmnohkbagfeq/Build/Products/Debug-iphonesimulator/MapboxGeocoder.framework/MapboxGeocoder
Reason: image not found
```
If an Obj-C application fails like this, add `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES` to the build settings for that target.
/cc @ericdeveloper @1ec5
> Fix Obj-C example by forcing it to include Swift frameworks

- MapboxGeocoder/MBGeocoder.swift
Fixed inverted logic when checking that a batch query doesn’t contain too many queries.
Fixes #114.
/cc @frederoni @hervouinc
> Fix batch query count assertion

- MapboxGeocoder/MBGeocodeOptions.swift
Essentially copies the [API docs](https://www.mapbox.com/api-documentation/#request-format) for the `limit` parameter, clarifying what the upper limits are for `MBGeocodeOptions.maximumResultCount`.
Prompted by [this SO question](https://stackoverflow.com/q/46810774/2094275).
/cc @1ec5
> Document the upper limits of MBGeocodeOptions.maximumResultCount

- README.md
Closes https://github.com/mapbox/MapboxGeocoder.swift/issues/121 by replacing all instances of the "Mapbox iOS SDK" and the "Mapbox macOS SDK" to the Mapbox Maps SDK for iOS and macOS, as reflected in https://github.com/mapbox/mapbox-gl-native/issues/10385.
> Update product names in readme

- MapboxGeocoder.xcodeproj/project.pbxproj
- MapboxGeocoder/MBGeocodeOptions.swift
- MapboxGeocoderTests/BridgingTests.m
Fixes #128 
The migration to Swift 4 unexposed these initializers to Objective-C.
@1ec5 @bsudekum 👀
> Expose reverse and forward initializers to Obj-C

- MapboxGeocoder/MBPlacemark.swift
- MapboxGeocoderTests/ReverseGeocodingTests.swift
Previously, when a `GeocodedPlacemark` was encoded, the computed getter, which in this case contained a house number, would get appended to the name property and be decoded as a formatted address. Next time `name` was accessed, it applied the same format when the house number was already there so it did not round-trip through encoding→decoding properly.
@bsudekum @1ec5 👀
> Fix formatted address

- MapboxGeocoder.swift.podspec
CocoaPods 1.4.0 supports a [`swift_version` setting in podspecs](https://blog.cocoapods.org/CocoaPods-1.4.0/#swift-version-dsl), so this adds that.
CocoaPods also says that the `.swift-version` file is being deprecated, but they’re not the only consumers of this file, so let's leave it around for the time being.
/cc @frederoni
> Specify Swift version in podspec

- MapboxGeocoder.xcodeproj/project.pbxproj
This change embeds MapboxGeocoder.framework into the Swift and Objective-C example applications.
/cc @captainbarbosa
> Embed framework in example applications

- MapboxGeocoder.xcodeproj/project.pbxproj
- MapboxGeocoder/MBGeocodeOptions.swift
- MapboxGeocoder/MBGeocoder.swift
- MapboxGeocoderTests/BatchForwardGeocodingTests.swift
- MapboxGeocoderTests/BatchGeocodingTests.swift
- MapboxGeocoderTests/fixtures/permanent_forward_multiple_no_results.json
- MapboxGeocoderTests/fixtures/permanent_forward_multiple_valid.json
- MapboxGeocoderTests/fixtures/permanent_forward_single_no_results.json
- MapboxGeocoderTests/fixtures/permanent_forward_single_valid.json
- MapboxGeocoderTests/fixtures/permanent_invalid.json
- MapboxGeocoderTests/fixtures/permanent_invalid_token.json
- MapboxGeocoderTests/fixtures/permanent_invalid_token_scope.json
- MapboxGeocoderTests/fixtures/permanent_reverse_multiple_no_results.json
- MapboxGeocoderTests/fixtures/permanent_reverse_multiple_valid.json
- MapboxGeocoderTests/fixtures/permanent_reverse_single_no_results.json
- MapboxGeocoderTests/fixtures/permanent_reverse_single_valid.json
Fixes https://github.com/mapbox/MapboxGeocoder.swift/issues/147.
Improves handling of logic around setting the desired Mapbox Geocoding API endpoint when using MBGeocodeOptions.
cc @kbauhaus
> Fix batch geocoding request handling

- MapboxGeocoder/MBGeocoder.swift
Static declarations are implicitly final so use `public` access modifier instead of `open`.
/cc @1ec5
> Fix compiler warning

- MapboxGeocoder/MBPlacemark.swift
- MapboxGeocoder/MBPlacemarkScope.swift
- MapboxGeocoderTests/ForwardGeocodingTests.swift
Fixes #156 Add relevance property to GeocodedPlacemark
cc @1ec5
> Encode and Decode Placemark.relevance

- MapboxGeocoder/MBGeocoder.swift
Fixes #160 Carthage Installation Fails when building for watchOS.
The cross-compiled fat file consists of `i386 armv7k arm64_32`, however, the `if arch(i386)` compilation directive does _not_ catch the i386 architecture when compiling for watchOS simulator despite `sysctlbyname("hw.cputype")` indicating x86 `CPU_TYPE_X86`.
This change works around this by checking for os when it should be checking for arch. I've also made the compilation directive exhaustive by adding an `unknown` chip.
Also, we should get Xcode 10 bots up and running.
@1ec5 @hyerra
> Fix non-exhaustive chip check

- MapboxGeocoder/MBGeocodeOptions.swift
Corrected an incorrect argument name in a documentation comment that produced the following warning in the navigation SDK:
```
/path/to/mapbox-navigation-ios/Carthage/Build/iOS/MapboxGeocoder.framework/Headers/MapboxGeocoder-Swift.h:473:12: Parameter 'location' not found in the function declaration
/path/to/mapbox-navigation-ios/Example/MBViewController.m:6:9: While building module 'MapboxNavigation' imported from /path/to/mapbox-navigation-ios/Example/MBViewController.m:6:
/Users/mxn/Library/Developer/Xcode/DerivedData/MapboxNavigation-alytgpeiocddhmempehvwkpsbezh/Build/Products/Debug-iphonesimulator/MapboxNavigation.framework/Headers/MapboxNavigation-Swift.h:174:9: While building module 'MapboxGeocoder' imported from /Users/mxn/Library/Developer/Xcode/DerivedData/MapboxNavigation-alytgpe …
```
> Fix argument name in documentation

- MapboxGeocoder/MBGeocoder.swift
This is a followup to #175 that dispatches the error handler on the main thread, avoiding undefined behavior if `Geocoder.geocode(_:completionHandler:)` is called on a background thread.
/cc @frederoni @kbauhaus
> Dispatch error handler on main queue

- MapboxGeocoder.xcodeproj/project.pbxproj
- MapboxGeocoder/MBGeocoder.swift
- MapboxGeocoder/MBPlacemark.swift
- MapboxGeocoder/MBPlacemarkPrecision.h
- MapboxGeocoder/MBPlacemarkPrecision.m
- MapboxGeocoder/MapboxGeocoder.h
Added the [`Placemark.precision`](https://docs.mapbox.com/api/search/#intersection-search) property to match the Geocoding API. Fixed an issue where the `formattedName` of an intersection placemark contained only one street but not the cross street.
/cc @frederoni @miccolis
> Add precision property to Placemark

- Cartfile.private
- Cartfile.resolved
Updates the Maps SDK to v5.0.0, which was [just released this week](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v5.0.0).
> Update Maps SDK to v5.0.0

- .circleci/config.yml
- MapboxGeocoder/MBPlacemark.swift
Added an initializer for Placemark that takes something other than a Decoder.
Fixes #201.
> Added Placemark initializer

- Cartfile.private
- Cartfile.resolved
- MapboxGeocoder.xcodeproj/project.pbxproj
- Sources/MapboxGeocoder/MBGeocoder.swift
Use `MBXAccessToken` as default access token. This change is required because CarPlay is using `MapboxGeocoder.swift` for searching.
> Use MBXAccessToken as default access token.
