MBGeocoder/MapboxGeocoder.swift

Remove tiles from API endpoint URL

---

MBGeocoder/MapboxGeocoder.swift

This PR migrates to the v5 endpoint and also limits precision of coordinates.
/cc @sbma44 @incanus @bleege

Migrate to v5 endpoint

---

Geocoder Example.xcodeproj/project.pbxproj
Geocoder Example.xcodeproj/xcshareddata/xcschemes/MapboxGeocoder.xcscheme
Geocoder Example.xcodeproj/xcshareddata/xcschemes/Unit Tests.xcscheme
Podfile
README.md
Unit Tests/Info.plist
Unit Tests/UnitTests.swift
Unit Tests/fixtures/reverse_invalid.json
Unit Tests/fixtures/reverse_valid.json

First cut with some minimal testing, but now we have a framework for adding more. In Swift! 
Tests passed before rebase; merging.

fixes #11: add unit tests

---

Geocoder Example.xcodeproj/project.pbxproj

Don't target the example app for tests

---

MBGeocoder/MapboxGeocoder.swift

The Geocoding API now includes telephone numbers in POI results.
/cc @sbma44

Include telephone number in POI results

---

MapboxGeocoder/MBGeocoder.swift

Added a parameter to filter forward geocoding results by scope.

Filter by scope

---

Geocoder Example/ViewController.m
Geocoder Example/ViewController.swift

Give a bit of friendly advice in the example project, rather than `Error calculating directions: Optional(Error Domain=com.octokit.swift Code=401 "(null)”)`.
Refs https://github.com/mapbox/MapboxDirections.swift/pull/36
/cc @1ec5

Assert that MapboxAccessToken has been set

---

MapboxGeocoder/MBGeocoder.swift
MapboxGeocoder/MBGeocoderConfiguration.swift

Added the ability to specify a custom host for the server API.

Add host option

---

MapboxGeocoder/MBGeocoder.swift

When a request fails due to rate limiting, include the number of previous requests made and the time interval in which they were made in the returned error. Also include the server error message for other errors, such as invalid input errors.
/ref mapbox/MapboxDirections.swift#47

Provide more details in rate limit error

---

Geocoder Example/Info.plist
Geocoder Example/Launch Screen.storyboard
Geocoder Example/ViewController.swift
MapboxGeocoder.xcodeproj/project.pbxproj

Added a launch screen storyboard to the example applications so that it doesn’t get letterboxed on modern iOS versions.

Add launch screen to example apps

---

README.md

Fix use of optional param placemarks

---

README.md

This is probably obvious to many, but I have designed a better idiot and I am him. cc @1ec5 for the review

Point to releases page for framework downloads

---

MapboxGeocoder.xcodeproj/project.pbxproj

Set BITCODE_GENERATION_MODE

---

MapboxGeocoder.xcodeproj/project.pbxproj

```bash
pod deintegrate
gem install cocoapods --pre # 1.1.0.rc.1
pod install
```
/cc @bsudekum @boundsj

Added SWIFT_VERSION everywhere

---

MapboxGeocoder/MBGeocodeOptions.swift
MapboxGeocoder/MBRectangularRegion.swift

Documented a few limitations that have been added to api-documentation recently. Also added documentation for a previously undocumented initializer.
/cc @tmcw

Document limitations

---

MapboxGeocoder/MBGeocodeOptions.swift
MapboxGeocoder/MBGeocoder.swift
MapboxGeocoder/MBPlacemark.swift
MapboxGeocoder/MBRectangularRegion.swift

Adopt new access levels
@1ec5 👀

New access levels

---

MapboxGeocoder.swift.podspec

Override SWIFT_VERSION

---

MapboxGeocoder/MBPlacemarkScope.h
MapboxGeocoder/MBPlacemarkScope.swift

looks to me like `MBPlacemarkScopeAll` will grab this safely but :eyes: appreciated

add poi.landmark

---

MapboxGeocoder/MBGeocoder.swift
MapboxGeocoderTests/GeocoderTests.swift

Cherry-picked #91 into the master branch, just in case a final Swift 2.3 release ends up happening.
/cc @Eldorado234

Fix parsing of rate limit error response

---

MapboxGeocoder.xcodeproj/xcshareddata/xcschemes/Example (Swift).xcscheme
MapboxGeocoder.xcodeproj/xcshareddata/xcschemes/MapboxGeocoder Mac.xcscheme

Missed a couple schemes in #93.

Upgrade schemes to Xcode 8.2

---

MapboxGeocoder/MBGeocoder.swift
README.md

Fixes https://github.com/mapbox/MapboxGeocoder.swift/issues/138

Expose the batch geocoding function to Objective-C

---

Cartfile.resolved
MapboxGeocoderTests/ForwardGeocodingTests.swift
circle.yml

Will deactivate Bitrise bots after a couple of runs with CircleCI.
cc @akitchen @JThramer

Migrate to CircleCI

---

MapboxGeocoder/MBGeocoder.swift
README.md

🚧  Do not merge until API documentation changes land 🚧 
This PR updates links to the API docs to match the new URL structure.
cc @mapbox/docs

[DNM] Updates URLs for API documentation

---

README.md

Add a note about Geocoding API pricing and update docs URLs in README
